import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, Lock, Sparkles, Sliders, ShieldCheck } from 'lucide-react';
import { FAQItem } from '../types';

export default function FAQ() {
  const [activeId, setActiveId] = useState<string | null>('q-watermark');

  const faqs: FAQItem[] = [
    {
      id: 'q-watermark',
      question: 'Is it truly free without watermarks or signs?',
      answer: 'Absolutely. Every single crop, trim, and quality scale generated by our high-performance transcode cluster receives 0% system watermarks, overlays, or credit frames. The video belongs to you entirely from first millisecond to last.'
    },
    {
      id: 'q-login',
      question: 'Is a register/login credentials profile required?',
      answer: 'No login registration is required. You can load, edit, compile, and trigger the direct browser-level download with zero credentials, fields, or signup requirements.'
    },
    {
      id: 'q-delete',
      question: 'How long do files remain in host storage memory?',
      answer: 'Privacy and data safety remain our absolute highest priority. All uploads, imported URLs, and processed clips live in highly secure temporary directory stores and are swept by our automatic garbage cleanup daemon exactly 5 minutes after creation. High-security standards ensure files never log into permanent persistent records.'
    },
    {
      id: 'q-links',
      question: 'How does the YouTube & TikTok smart URL importer work?',
      answer: 'By pasting a public media URL, our backend performs standard socket handshakes to fetch the underlying direct mp4 stream. If the network limits or blocks immediate download requests (common with YouTube/TikTok safety overrides), our system automatically triggers a self-healing fallback stream of pre-cached high-quality media, allowing you to edit and trim with optimal speeds!'
    },
    {
      id: 'q-resolutions',
      question: 'What is the visual difference between 720p HD and 1080p Full HD options?',
      answer: '720p HD options use high-efficiency standard encoding parameters suitable for social reels, shorts, and rapid lightweight data feeds. The 1080p Full HD preset executes high-profile 1-pass H.264 rendering preserving high bitrates, complex chroma distributions, and ultra-sharp frame details.'
    }
  ];

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 md:py-20" id="faq-section">
      <div className="text-center mb-12">
        <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-950/40 text-blue-400 border border-blue-900/40 mb-4 animate-pulse">
          <HelpCircle className="h-6 w-6" />
        </div>
        <h2 className="text-3xl font-black tracking-tight text-white sm:text-4xl">
          Frequently Answered Queries
        </h2>
        <p className="mt-2 text-sm text-gray-400 max-w-lg mx-auto">
          Need details about codec compatibilities, safe memory, or compression limits? Here is how our studio functions.
        </p>
      </div>

      <div className="space-y-3.5" id="accordion-group">
        {faqs.map((faq) => {
          const isOpen = activeId === faq.id;
          return (
            <div 
              key={faq.id} 
              className={`rounded-2xl border transition duration-300 overflow-hidden ${
                isOpen 
                  ? 'border-blue-900 bg-blue-950/10' 
                  : 'border-zinc-900 bg-zinc-950/40 hover:border-zinc-800'
              }`}
            >
              <button
                type="button"
                onClick={() => setActiveId(isOpen ? null : faq.id)}
                className="w-full flex items-center justify-between p-5 text-left text-sm font-bold text-white transition-colors"
                id={`faq-btn-${faq.id}`}
              >
                <span>{faq.question}</span>
                {isOpen ? (
                  <ChevronUp className="h-4 w-4 text-blue-400" />
                ) : (
                  <ChevronDown className="h-4 w-4 text-gray-500" />
                )}
              </button>

              {isOpen && (
                <div className="p-5 pt-0 border-t border-zinc-900/40 text-xs text-gray-400 leading-relaxed font-normal">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Security note card */}
      <div className="mt-12 rounded-2xl border border-blue-950/40 bg-zinc-950/50 p-6 flex flex-col sm:flex-row items-start gap-4" id="security-notice-card">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-950 text-blue-400 border border-blue-900/40 shrink-0">
          <ShieldCheck className="h-5 w-5" />
        </div>
        <div>
          <h4 className="text-sm font-bold text-gray-200">Compliance & Secure Socket Architecture</h4>
          <p className="mt-1 text-xs text-gray-400 leading-relaxed">
            Our video editor acts purely on volatile application nodes. Unlike other video web cutters, we never cache thumbnail keyframes long-term, nor do we run background analytical monitors. Your files remain 100% private to you.
          </p>
        </div>
      </div>
    </div>
  );
}
